---
- name: Set provision username fact to ansible
  ansible.builtin.set_fact:
    provision_user_username: ansible
  when: provision_user_username is not defined

- name: Prompt user for provision username
  ansible.builtin.pause:
    prompt: Enter username for provision user
    echo: yes
  when: provision_user_username == ""
  register: _provision_username_input

- name: Set provision username fact
  ansible.builtin.set_fact:
    provision_user_username: "{{ _provision_username_input.user_input }}"
  when: provision_user_username == ""

- name: Prompt user for provision password
  ansible.builtin.pause:
    prompt: >-
      Enter a password for provision user, or just press enter to have a random password generated
    echo: no
  when: provision_user_password is not defined or provision_user_password == ""
  register: _provision_password_input

- name: Set provision password to password provided by user interactively
  ansible.builtin.set_fact:
    provision_user_password: "{{ _provision_password_input.user_input }}"
  when: >
    _provision_password_input.user_input != "" and
    provision_user_password | default("") == ""

- name: Set provision password to random password if none specified
  ansible.builtin.set_fact:
    provision_user_password: "{{
      lookup('community.general.random_string',
             length=32, min_lower=5, min_upper=5, min_special=5, min_numeric=5)
      }}"
  when: provision_user_password | default("") == ""

- name: Set provision user ssh pass fact
  ansible.builtin.set_fact:
    provision_user_ssh_password: "{{ provision_user_password }}"
  when: provision_ssh_password_authentication | bool and provision_user_ssh_password == ""

- name: Export provision user facts
  ansible.builtin.set_fact:
    provision_user_username: "{{ provision_user_username }}"
    provision_user_password: "{{ provision_user_password }}"
    provision_user_keep: "{{ provision_user_keep }}"
    provision_user_ssh_password: "{{ provision_user_ssh_password }}"
    provision_user_private_key_file: "{{ provision_user_private_key_file }}"
